AWS_PROFILE ?= default
REGION ?= eu-west-1

deploy-ec2:
	aws --profile $(AWS_PROFILE) --region $(REGION) cloudformation deploy \
	  --stack-name ec2-web-stack \
	  --template-file cloudformation/ec2-stack.yml \
	  --capabilities CAPABILITY_NAMED_IAM

outputs-ec2:
	aws --profile $(AWS_PROFILE) --region $(REGION) cloudformation describe-stacks \
	  --stack-name ec2-web-stack \
	  --query "Stacks[0].Outputs"

deploy-lambda:
	aws --profile $(AWS_PROFILE) --region $(REGION) cloudformation deploy \
	  --stack-name lambda-stack \
	  --template-file cloudformation/lambda-stack.yml \
	  --capabilities CAPABILITY_NAMED_IAM

outputs-lambda:
	aws --profile $(AWS_PROFILE) --region $(REGION) cloudformation describe-stacks \
	  --stack-name lambda-stack \
	  --query "Stacks[0].Outputs"
